Auto Fri Oct  9 01:49:16 PM CEST 2026.

diff --git a/helpers/templates/quick/awg-quick b/helpers/templates/quick/awg-quick
--- a/helpers/templates/quick/awg-quick
+++ b/helpers/templates/quick/awg-quick
@@ -46,8 +46,14 @@ die()  { printf ' \033[1;31m ❌ CRITICAL:\033[0;1m [%s] - %s!\033[0m\n' "$PROGR
 #cmd ip r; log "log"; warn "warn"; err "err"; die "die"
 
 AWG_BIN="$(which ${AWG_NAME})"
-[[ -f "${AWG_BIN}" ]] > /dev/null 2>&1 || { die "The originaly $AWG_NAME does not exist!"; exit 1; }
-[[ "${LNK_NAME}" = "${AWG_NAME}" || -r "${LNK_NAME}" ]] > /dev/null 2>&1 || { cd ${SELF_DIR} && ln -s "${AWG_NAME}" "${LNK_NAME}" 2>/dev/null || die "Symlink $LNK_NAME create failed!"; }
+#[[ -f "${AWG_BIN}" ]] > /dev/null 2>&1 || { die "The originaly $AWG_NAME does not exist!"; }
+[[ -z "${AWG_BIN}" || ! -x "${AWG_BIN}" ]] > /dev/null 2>&1 || { die "The original binary '${AWG_NAME}' does not exist or is not executable."; }
+#[[ "${LNK_NAME}" = "${AWG_NAME}" || -r "${LNK_NAME}" ]] > /dev/null 2>&1 || { cd ${SELF_DIR} && ln -s "${AWG_NAME}" "${LNK_NAME}" 2>/dev/null || die "Symlink $LNK_NAME create failed!"; }
+if [[ ! -e "${SELF_DIR}/${LNK_NAME}" && ! -L "${SELF_DIR}/${LNK_NAME}" ]]; then
+    if ! ln -s "${AWG_BIN}" "${SELF_DIR}/${LNK_NAME}"; then
+        die "Failed to create symlink '${LNK_NAME}' to '${AWG_BIN}'."
+    fi
+fi
 
 #-> Дальше идет код из оригинального скрипта wg-quick, с небольшими изменениями в функциях set_dns и unset_dns (dns-hatchet),
 # чтобы использовать tmpfs для /etc/resolv.conf, если openresolv не установлен. 
